/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;


import ClasePrincipal.MetodosLogin;
import javax.swing.JOptionPane;



/**
 *
 * @author LABPC02-07
 */
public class fmr_Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    MetodosLogin metodos = new MetodosLogin();
    public fmr_Registro() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(lblReg, "src/Imagenes2/reg.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblFondo, "src/Imagenes2/modenas.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblNombre, "src/Imagenes2/Usuario.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblApe, "src/Imagenes2/ape.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblTel, "src/Imagenes2/tel.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblCorreo, "src/Imagenes2/cor.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblCon, "src/Imagenes2/Contrase.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblCcontra, "src/Imagenes2/ccontra.png");
        
    } // RA VE

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblReg = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDinero = new javax.swing.JTextField();
        pswConfirmar = new javax.swing.JPasswordField();
        pswContra = new javax.swing.JPasswordField();
        lblNombre = new javax.swing.JLabel();
        lblCcontra = new javax.swing.JLabel();
        lblApe = new javax.swing.JLabel();
        lblTel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblCon = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbxChekear = new javax.swing.JCheckBox();
        lblFondo = new javax.swing.JLabel();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(lblReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 160, 50));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 130, 30));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 130, 30));

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, 30));

        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 130, 30));

        txtDinero.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(txtDinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 80, 30));
        jPanel1.add(pswConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 352, 130, 30));

        pswContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pswContraKeyTyped(evt);
            }
        });
        jPanel1.add(pswContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 130, 30));
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));
        jPanel1.add(lblCcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 110, 40));
        jPanel1.add(lblApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, 40));
        jPanel1.add(lblTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 40));

        jLabel1.setText("Dinero");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 40));
        jPanel1.add(lblCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 110, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ok.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 90, 60));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 70, 50));

        cbxChekear.setText("Chekear");
        jPanel1.add(cbxChekear, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 460));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        
        if(txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() ||
                txtCorreo.getText().isEmpty() || txtTelefono.getText().isEmpty() ||
                pswContra.getText().isEmpty() || pswConfirmar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos vacios");      
        }else{         
            if(pswContra.getText().equals(pswConfirmar.getText())){
                
                if(txtTelefono.getText().length() != 10){
                    JOptionPane.showMessageDialog(null, "Numero no valido");
                }else{
                    metodos.RegistrarCliente(txtApellido.getText(), txtCorreo.getText(), txtNombre.getText(),
                            txtDinero.getText(), txtTelefono.getText(), "CL", pswContra.getText()); 
                    
                }
                             
            }
            else {
                
                JOptionPane.showMessageDialog(null, "No coinciden las claves");
            } 
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char opcion = evt.getKeyChar();
        if (Character.isDigit(opcion)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ERROR");
            
                     
        } else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "ERROR");
         txtApellido.setCursor(null);
     }
        
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
         char opcion = evt.getKeyChar();
        if (Character.isDigit(opcion)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ERROR");
            
                     
        } else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "ERROR");
         txtApellido.setCursor(null);
     }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        
    char opcion= evt.getKeyChar();
     
     if(Character.isLetter(opcion))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "ERROR");
         txtTelefono.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "ERROR");
         txtTelefono.setCursor(null);
     }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       fmr_Login2 log = new fmr_Login2();
       this.setVisible(false);
       log.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void pswContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswContraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pswContraKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmr_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmr_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmr_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmr_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmr_Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbxChekear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblApe;
    private javax.swing.JLabel lblCcontra;
    private javax.swing.JLabel lblCon;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblReg;
    private javax.swing.JLabel lblTel;
    private javax.swing.JPasswordField pswConfirmar;
    private javax.swing.JPasswordField pswContra;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDinero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
