/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

//import formularios.frmLogIn;

import ClasePrincipal.MetodosLogin;
import java.awt.Color;
import javax.swing.JOptionPane;


/**
 *
 * @author Antonio
 */

public class frmRegistroF extends javax.swing.JFrame {

    int xMouse; 
    int yMouse; 
    MetodosLogin metodos = new MetodosLogin();
    public frmRegistroF() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBlanco = new javax.swing.JPanel();
        pnlRojoArriba = new javax.swing.JPanel();
        pnlVolver = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        lblBack1 = new javax.swing.JLabel();
        pnlRojoAbajo = new javax.swing.JPanel();
        lblRegistro = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtTelefono = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pswContra = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlRegistrar = new javax.swing.JPanel();
        lblRegistrar = new javax.swing.JLabel();
        pswConfirmar = new javax.swing.JPasswordField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDinero = new javax.swing.JTextField();
        lblPass1 = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        lblCorreo1 = new javax.swing.JLabel();
        lblPass2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBlanco.setBackground(new java.awt.Color(255, 255, 255));

        pnlRojoArriba.setBackground(new java.awt.Color(228, 0, 43));
        pnlRojoArriba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnlRojoArribaMouseDragged(evt);
            }
        });
        pnlRojoArriba.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlRojoArribaMousePressed(evt);
            }
        });

        pnlVolver.setBackground(new java.awt.Color(24, 120, 93));
        pnlVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblSalir.setBackground(new java.awt.Color(24, 120, 93));
        lblSalir.setFont(new java.awt.Font("Gill Sans MT", 0, 36)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setText("X");
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.setOpaque(true);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });

        lblBack1.setBackground(new java.awt.Color(24, 120, 93));
        lblBack1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblBack1.setForeground(new java.awt.Color(255, 255, 255));
        lblBack1.setText("←");
        lblBack1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack1.setOpaque(true);
        lblBack1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBack1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBack1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBack1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout pnlVolverLayout = new javax.swing.GroupLayout(pnlVolver);
        pnlVolver.setLayout(pnlVolverLayout);
        pnlVolverLayout.setHorizontalGroup(
            pnlVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBack1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSalir)
                .addGap(15, 15, 15))
        );
        pnlVolverLayout.setVerticalGroup(
            pnlVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVolverLayout.createSequentialGroup()
                .addGroup(pnlVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBack1))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlRojoArribaLayout = new javax.swing.GroupLayout(pnlRojoArriba);
        pnlRojoArriba.setLayout(pnlRojoArribaLayout);
        pnlRojoArribaLayout.setHorizontalGroup(
            pnlRojoArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlRojoArribaLayout.setVerticalGroup(
            pnlRojoArribaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRojoArribaLayout.createSequentialGroup()
                .addComponent(pnlVolver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlRojoAbajo.setBackground(new java.awt.Color(24, 120, 93));

        javax.swing.GroupLayout pnlRojoAbajoLayout = new javax.swing.GroupLayout(pnlRojoAbajo);
        pnlRojoAbajo.setLayout(pnlRojoAbajoLayout);
        pnlRojoAbajoLayout.setHorizontalGroup(
            pnlRojoAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlRojoAbajoLayout.setVerticalGroup(
            pnlRojoAbajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 66, Short.MAX_VALUE)
        );

        lblRegistro.setFont(new java.awt.Font("Gill Sans MT", 0, 48)); // NOI18N
        lblRegistro.setText("Registro");

        lblUsuario.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblUsuario.setText("Apellido:");

        txtApellido.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(204, 204, 204));
        txtApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtApellidoMousePressed(evt);
            }
        });
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        lblCorreo.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblCorreo.setText("Correo:");

        lblPass.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblPass.setText("Contraseña:");

        jSeparator2.setBackground(new java.awt.Color(228, 0, 43));

        txtTelefono.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(204, 204, 204));
        txtTelefono.setToolTipText("");
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtTelefonoMousePressed(evt);
            }
        });
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(228, 0, 43));

        pswContra.setForeground(new java.awt.Color(204, 204, 204));
        pswContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pswContraMousePressed(evt);
            }
        });
        pswContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswContraActionPerformed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(228, 0, 43));
        jSeparator3.setForeground(new java.awt.Color(228, 0, 43));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario_1.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Correo.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Pass.png"))); // NOI18N

        pnlRegistrar.setBackground(new java.awt.Color(24, 120, 93));
        pnlRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlRegistrarMouseExited(evt);
            }
        });

        lblRegistrar.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrar.setText("Registrar");
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblRegistrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistrarLayout = new javax.swing.GroupLayout(pnlRegistrar);
        pnlRegistrar.setLayout(pnlRegistrarLayout);
        pnlRegistrarLayout.setHorizontalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblRegistrar)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlRegistrarLayout.setVerticalGroup(
            pnlRegistrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistrarLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblRegistrar)
                .addGap(8, 8, 8))
        );

        pswConfirmar.setForeground(new java.awt.Color(204, 204, 204));
        pswConfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pswConfirmarMousePressed(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(204, 204, 204));
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtNombreMousePressed(evt);
            }
        });
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtCorreo.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(204, 204, 204));
        txtCorreo.setToolTipText("");
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtCorreoMousePressed(evt);
            }
        });
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoKeyTyped(evt);
            }
        });

        txtDinero.setFont(new java.awt.Font("Gill Sans MT", 0, 16)); // NOI18N
        txtDinero.setForeground(new java.awt.Color(204, 204, 204));
        txtDinero.setToolTipText("");
        txtDinero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtDineroMousePressed(evt);
            }
        });
        txtDinero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDineroActionPerformed(evt);
            }
        });

        lblPass1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblPass1.setText("Dinero:");

        lblUsuario1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblUsuario1.setText("Nombre:");

        lblCorreo1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblCorreo1.setText("Telefono:");

        lblPass2.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        lblPass2.setText("Ccontraseña:");

        javax.swing.GroupLayout pnlBlancoLayout = new javax.swing.GroupLayout(pnlBlanco);
        pnlBlanco.setLayout(pnlBlancoLayout);
        pnlBlancoLayout.setHorizontalGroup(
            pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRojoArriba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlRojoAbajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBlancoLayout.createSequentialGroup()
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBlancoLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(lblRegistro))
                    .addGroup(pnlBlancoLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(pnlRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlancoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblPass1)
                .addGap(18, 18, 18)
                .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlancoLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlancoLayout.createSequentialGroup()
                        .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlancoLayout.createSequentialGroup()
                                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlBlancoLayout.createSequentialGroup()
                                        .addComponent(lblPass2)
                                        .addGap(18, 18, 18)
                                        .addComponent(pswConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlBlancoLayout.createSequentialGroup()
                                        .addComponent(lblPass)
                                        .addGap(18, 18, 18)
                                        .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)))
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlancoLayout.createSequentialGroup()
                        .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuario1)
                            .addGroup(pnlBlancoLayout.createSequentialGroup()
                                .addComponent(lblUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(118, 118, 118))))
            .addGroup(pnlBlancoLayout.createSequentialGroup()
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlBlancoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCorreo)
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlBlancoLayout.createSequentialGroup()
                            .addGap(246, 246, 246)
                            .addComponent(jLabel1))
                        .addGroup(pnlBlancoLayout.createSequentialGroup()
                            .addGap(62, 62, 62)
                            .addComponent(lblCorreo1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlBlancoLayout.createSequentialGroup()
                            .addGap(247, 247, 247)
                            .addComponent(jLabel2))
                        .addGroup(pnlBlancoLayout.createSequentialGroup()
                            .addGap(245, 245, 245)
                            .addComponent(jLabel3))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBlancoLayout.createSequentialGroup()
                    .addContainerGap(173, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(119, 119, 119)))
        );
        pnlBlancoLayout.setVerticalGroup(
            pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBlancoLayout.createSequentialGroup()
                .addComponent(pnlRojoArriba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCorreo1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass))
                .addGap(2, 2, 2)
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pswConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPass1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRojoAbajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(pnlBlancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlBlancoLayout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(536, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlBlanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
       
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        
    }//GEN-LAST:event_lblSalirMouseExited

    private void pnlRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegistrarMouseEntered
       pnlRegistrar.setBackground(new Color(255,20,0));
    }//GEN-LAST:event_pnlRegistrarMouseEntered

    private void pnlRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegistrarMouseExited
        pnlRegistrar.setBackground(new Color(228,0,43));
    }//GEN-LAST:event_pnlRegistrarMouseExited

    private void pnlRojoArribaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRojoArribaMousePressed
        xMouse = evt.getX(); 
        yMouse = evt.getY();
    }//GEN-LAST:event_pnlRojoArribaMousePressed

    private void pnlRojoArribaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRojoArribaMouseDragged
       int x = evt.getXOnScreen(); 
       int y = evt.getYOnScreen(); 
       this.setLocation(x-xMouse, y-yMouse);       
    }//GEN-LAST:event_pnlRojoArribaMouseDragged

    private void pnlRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRegistrarMouseClicked
    if(txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() ||
                txtTelefono.getText().isEmpty() || txtTelefono.getText().isEmpty() ||
                pswContra.getText().isEmpty() || pswConfirmar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos vacios");      
        }else{         
            if(pswContra.getText().equals(pswConfirmar.getText())){
                
                if(txtTelefono.getText().length() != 10){
                    JOptionPane.showMessageDialog(null, "Numero no valido");
                }else{
                    metodos.RegistrarCliente(txtApellido.getText(), txtTelefono.getText(), txtNombre.getText(),
                            txtDinero.getText(), txtTelefono.getText(), "CL", pswContra.getText()); 
                    
                }
                             
            }
            else {
                
                JOptionPane.showMessageDialog(null, "No coinciden las claves");
            } 
        }   
        
    }//GEN-LAST:event_pnlRegistrarMouseClicked

    private void txtApellidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMousePressed
        if(txtApellido.getText().equals("Ingrese su nombre de usuario")){
            txtApellido.setText("");
            txtApellido.setForeground(Color.BLACK);    
        }
        if(pswContra.getText().isEmpty()){
            pswContra.setText("Contraseña");
            pswContra.setForeground(Color.GRAY);            
        }
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Ingrese su correo");
            txtTelefono.setForeground(Color.GRAY);
        }            
    }//GEN-LAST:event_txtApellidoMousePressed

    private void txtTelefonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMousePressed
        if(txtTelefono.getText().equals("Ingrese su correo")){
            txtTelefono.setText("");
            txtTelefono.setForeground(Color.BLACK);    
        }
        if(pswContra.getText().isEmpty()){
            pswContra.setText("Contraseña");
            pswContra.setForeground(Color.GRAY);            
        }
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Ingrese su nombre de usuario");
            txtApellido.setForeground(Color.GRAY);
        }            
    }//GEN-LAST:event_txtTelefonoMousePressed

    private void pswContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswContraMousePressed
       if(pswContra.getText().equals("Contraseña")){
            pswContra.setText("");
            pswContra.setForeground(Color.BLACK);    
        }
        if(txtTelefono.getText().isEmpty()){
            txtTelefono.setText("Ingrese su correo");
            txtTelefono.setForeground(Color.GRAY);            
        }
        if(txtApellido.getText().isEmpty()){
            txtApellido.setText("Ingrese su nombre de usuario");
            txtApellido.setForeground(Color.GRAY);
        }          
    }//GEN-LAST:event_pswContraMousePressed

    private void lblRegistrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMousePressed
        
    }//GEN-LAST:event_lblRegistrarMousePressed

    private void lblRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseEntered
      
    }//GEN-LAST:event_lblRegistrarMouseEntered

    private void lblBack1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack1MouseEntered
        
    }//GEN-LAST:event_lblBack1MouseEntered

    private void lblBack1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack1MouseExited
        
    }//GEN-LAST:event_lblBack1MouseExited

    private void lblBack1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBack1MouseClicked
       formularios.frmLogIn log = new formularios.frmLogIn();
       this.setVisible(false);
       log.setVisible(true);
    }//GEN-LAST:event_lblBack1MouseClicked

    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
         if(txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty() ||
                txtCorreo.getText().isEmpty() || txtTelefono.getText().isEmpty() ||
                pswContra.getText().isEmpty() || pswConfirmar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Campos vacios");      
        }else{         
            if(pswContra.getText().equals(pswConfirmar.getText())){
                
                if(txtTelefono.getText().length() != 10){
                    JOptionPane.showMessageDialog(null, "Numero no valido");
                }else{
                    metodos.RegistrarCliente(txtApellido.getText(), txtCorreo.getText(), txtNombre.getText(),
                            txtDinero.getText(), txtTelefono.getText(), "CL", pswContra.getText()); 
                    
                }
                             
            }
            else {
                
                JOptionPane.showMessageDialog(null, "No coinciden las claves");
            } 
        }   
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void pswConfirmarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswConfirmarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswConfirmarMousePressed

    private void txtNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMousePressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoMousePressed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void pswContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pswContraActionPerformed

    private void txtDineroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDineroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDineroMousePressed

    private void txtDineroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDineroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDineroActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char opcion = evt.getKeyChar();
        if (Character.isDigit(opcion)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ERROR");
            
                     
        } else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "ERROR");
         txtApellido.setCursor(null);
     }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
         char opcion = evt.getKeyChar();
        if (Character.isDigit(opcion)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "ERROR");
            
                     
        } else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "ERROR");
         txtApellido.setCursor(null);
     }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtCorreoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyTyped
        
    }//GEN-LAST:event_txtCorreoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char opcion= evt.getKeyChar();
     
     if(Character.isLetter(opcion))
     {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "ERROR");
         txtTelefono.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
         getToolkit().beep();
         evt.consume();
         JOptionPane.showMessageDialog(this, "ERROR");
         txtTelefono.setCursor(null);
     }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistroF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistroF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistroF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistroF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistroF().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblBack1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblRegistrar;
    private javax.swing.JLabel lblRegistro;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblUsuario1;
    private javax.swing.JPanel pnlBlanco;
    private javax.swing.JPanel pnlRegistrar;
    private javax.swing.JPanel pnlRojoAbajo;
    private javax.swing.JPanel pnlRojoArriba;
    private javax.swing.JPanel pnlVolver;
    private javax.swing.JPasswordField pswConfirmar;
    private javax.swing.JPasswordField pswContra;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDinero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
